### ISSUE TITLE
[Bug] Black screen after receiving via BTC address

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1142]
### What happened

- Send to Breez BTC address (with fee for expected conf after multiple blocks)
- See at receive via BTC address "Breez is processing your payment"
- Some hours later open Breez
- Click on the loading/sync icon at homescreen, see  "Processing incoming payment" or something like that loading
- Screen turns black

restart fixes it

### Logs

It happend just after 9, but logs at that time are missing?

```
2023-05-19 08:55:28.041 [ERR] BIND: Error in calling method rate
2023-05-19 08:55:28.042 [ERR] BIND: Error in calling method 'rate' with arguments: null.
2023-05-19 08:55:28.042 [ERR] BIND: Error in calling method 'rate' with error: PlatformException(rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup bs1.breez.technology: No address associated with hostname", rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup bs1.breez.technology: No address associated with hostname", Failed to invoke method rate, null).
2023-05-19 08:55:28.043 [INF] BIND: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup bs1.breez.technology: No address associated with hostname" method: rate
#0      BreezBridge._invokeMethodImmediate.<anonymous closure>.<anonymous closure> (package:breez/services/breezlib/breez_bridge.dart:967)
#1      _rootRunUnary (dart:async/zone.dart:1406)
#2      _CustomZone.runUnary (dart:async/zone.dart:1307)
#3      _FutureListener.handleError (dart:async/future_impl.dart:165)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779)
#5      Future._propagateToListeners (dart:async/future_impl.dart:800)
#6      Future._completeError (dart:async/future_impl.dart:575)
#7      _SuspendState._createAsyncStarCallback.<anonymous closure> (dart:async-patch/async_patch.dart:353)
#8      _rootRunUnary (dart:async/zone.dart:1406)
#9      _CustomZone.runUnary (dart:async/zone.dart:1307)
<asynchronous suspension>

2023-05-19 09:11:38.442 [INF] BIND: before invoking method immediate rate
```

### video

https://github.com/breez/breezmobile/assets/93143998/ce5d2217-7795-41ae-ad20-47eacb98d258

**Comment by MarnixCroes** [comment]
FYI, I just made a screenshot and in the screenshot the Breez screen is black.
Tried some more but cannot repro.
Other than that no issues, only the screenshot was black.

**Comment by erdemyerebasmaz** [comment]
@MarnixCroes We don't have a readily available solution to this but we're aware of this issue where the Breez Library does not restart after app spends several hours in the background on Graphene & Calyx OS.
