### ISSUE TITLE
Cannot create invoice on simnet

### ISSUE THREAD

**Issue by schjonhaug** [breez/breezmobile#1188]
Same setup as in https://github.com/breez/breezmobile/issues/1187, simnet is running nominal in Docker and I’m able to sync to the chain.

I’m trying to [receive payments](https://doc.breez.technology/Running-Breez-in-simnet.html#receiving-payments), and everything works fine until the last step where I’m supposed to paste a in a payment request.

```
❯ docker exec dev-breez "/lnd/lncli" -network=simnet getinfo | jq '.identity_pubkey'
"03cbea0e4877ba0bf0568afa1a58b777e26e7a0dc004392a71f9b46bc9c00dd66d"
❯ docker exec dev-btcd /start-btcctl.sh generate 6
[
  "649692fc22258b43a0c57e2d63f3697975fa221d0f9574bb234fb574e6769bd3",
  "35f9ddf94a391eb85c91ae4dda14f6caa7a299587c07e780458cc9301d362fc8",
  "6121ce18c3029612d7af6b130899dfbc99f3a0026e8ac4eadd74641839d6f46e",
  "5dd48fed1f3e5a39ceaa56cfa623d2e83e2a32437a928110f86ceaf11e411083",
  "2fa04269d5821228b38ff206d99ef2e2ff79199f311fb025bc7261f6d61d092e",
  "372c9d509d3fa0ffdb031266665e56e70f0c1e767f2641d40db56a7e36a0c21f"
]
❯ docker exec dev-alice "/root/go/bin/lncli" --network simnet newaddress np2wkh
{
    "address": "rk2VEUthpSFtwjAQuKtR5jWVeR9a66aEcg"
}
❯ docker exec dev-breez "/lnd/lncli" -network=simnet sendcoins rk2VEUthpSFtwjAQuKtR5jWVeR9a66aEcg 20000000

{
    "txid": "4eb02438b5d93a113b5ac67b5591c87e8492064e963178ca23cea29c3727b784"
}
❯ docker exec dev-btcd /start-btcctl.sh generate 6
[
  "26b7edbea41ae933e43df37cec5bd6bc0569cfbe8f708bf7dc9ebad888f5ace0",
  "62112d87d9414d23f918b3d2dcb7f1617067a0c7c15c990668eb36358ab962a9",
  "1e904db84d396d6d89b56e5d5ee9be4625648df54d32e18e5e6ad34ed70ce3b7",
  "11bf763d3aaea17b3f7c0864bbbf3f9224e19bddafc15aa0e5b0a6d0f2f5d0bc",
  "423b0ff71e23f2be8c7f1f546dd397799d276478f2a5fa260ba45fd5fa5d2741",
  "11411e0018577eb510b4a6ef9b1f63ec81c105d9a0a2670c9f258c8c81bb2287"
]
❯ docker exec dev-alice "/root/go/bin/lncli" -network=simnet openchannel --node_key 03cbea0e4877ba0bf0568afa1a58b777e26e7a0dc004392a71f9b46bc9c00dd66d --local_amt=200000 --connect=10.5.0.3:9735 --private
{
	"funding_txid": "bd350020f217e610f62e6e1977e93cb1742c8e4461acb1d01cb240fe6742a43b"
}
❯ docker exec dev-btcd /start-btcctl.sh generate 6
[
  "03625433ede90db2f251c374fd95b863ad586ae4a8e36764e641e81e05a3253a",
  "7636bea899e7c784e0272cc341a0e6d7229252b1d56b94f211cd836b7aaa99b5",
  "37ba016b16522d276d041921e63ba9a527c90d324cfa85ade73602442a019318",
  "07ebee74b7de8b456402ce3db89625bb047d7bda8a20b61dde3370ace57b2889",
  "238fc4c9d11824803fbc33390813141d89e9fa9deb4e3de34ea19c9d1203a541",
  "75dc1a7181fef9faffed8860e2228c8e9ff1929352451e3cb0e6369f2b50ce80"
]
```

![432A1016-72BA-4F7A-A005-D276A58D47FD_1_102_o](https://github.com/breez/breezmobile/assets/84225/d9e0925f-7959-4022-aaee-f1d9f203654e)

![5629052A-170F-40A2-8004-AC03E94250A1_1_102_o](https://github.com/breez/breezmobile/assets/84225/dd43c4a4-2376-4e11-9368-93779e59b741)

I noticed that the fee shows as 0.0% while this is not the case in the app running on mainnet.

Log from Xcode:

```
2023-08-14 20:28:40.497 [INF] BIND: validatePayment amount: 1000000, outgoing: false where maxAllowedToReceive: 4000000, maxAllowedToPay: 0, maxPaymentAmount: 4294967, reserveAmount: 0
2023-08-14 20:28:40.498 [INF] BIND: before invoking method lspList
lspList
2023-08-14 20:28:40.499 [INF] CLIENT: getBreezClientConnection - before Ping;
2023-08-14 20:28:40.593 [INF] CLIENT: getBreezClientConnection - after Ping; err: <nil>
2023-08-14 20:28:40.604 [INF] CLIENT: No channel opening params are available in lsp info
2023-08-14 20:28:40.604 [INF] CLIENT: No channel opening params are available in lsp info
2023-08-14 20:28:40.607 [INF] BIND: background task started
2023-08-14 20:28:40.608 [INF] BIND: LSP - status changed adding reconnect request
2023-08-14 20:28:40.611 [INF] BIND: before invoking method addInvoice
addInvoice
2023-08-14 20:28:40.611 [INF] ACCNT: Generated zero-conf invoice for amount: 1000000000
2023-08-14 20:28:40.611 [INF] ACCNT: zero-conf fee calculation option: lsp fee rate (proportional): 0 (minimum 0), total fees for channel: 0
2023-08-14 20:28:40.618 [WRN] INVC: client=2 for invoice notifications missed an update, add_index=0, new add event index=7
2023-08-14 20:28:40.618 [WRN] INVC: client=1 for invoice notifications missed an update, add_index=0, new add event index=7
2023-08-14 20:28:40.619 [INF] ACCNT: watchPayments - Invoice received by subscription
2023-08-14 20:28:40.619 [INF] DAEM: watchPayments - Invoice received by subscription
2023-08-14 20:28:40.622 [INF] ACCNT: Tracking invoice amount=1000000000, hash=[174 163 197 191 235 150 225 33 153 102 177 212 70 158 240 214 69 52 69 20 236 106 145 101 202 178 30 17 33 107 175 115]
2023-08-14 20:28:40.623 [INF] ACCNT: Generated payee invoice: lnsb10m1pjd4rncpp5463ut0ltjmsjrxtxk82yd8hs6ezng3g5a34fzew2kg0pzgtt4aesdqqcqzzsxqrrssrzjq0975rjgw7aqhuzk3tap5k9hwl3xu7sdcqzrj2n3lx6xhjwqphtx6qqqqyqqqqqqqqqqqqlgqqqqqqgqjqnp4qtmp6ke5wzsnac8ufhs6sxd3gmxfxvmkal0pa28wh7te4c6yruktqsp5t26tafar7ksuh57pys3tpfu8sya6gv65gw6s5gmhqwmsdnc0ty7s9qyyssq6rdmuhsmjgqhey9e5jxr77jq7j7qg6djtqvhex6vwc5lz2szycv5500u4sr9cwd3lep8x7sr6h9fuaerregtj90ez3nkd0juv20rn4cqrjujf6
2023-08-14 20:28:40.623 [INF] CLIENT: getBreezClientConnection - before Ping;
2023-08-14 20:28:40.630 [INF] CLIENT: getBreezClientConnection - after Ping; err: <nil>
2023-08-14 20:28:40.630 [INF] CLIENT: NewSyncNotifierClient - connection state = READY
2023-08-14 20:28:40.630 [INF] ACCNT: Register Payment pubkey = [2 86 29 238 199 110 109 160 85 229 210 159 116 114 155 216 103 40 248 34 78 126 10 179 97 141 118 28 145 126 250 183 31]
2023-08-14 20:28:40.641 [INF] ACCNT: RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees
2023-08-14 20:28:40.648 [ERR] BIND: failed to invoke method addInvoice PlatformException(Method Error, Error Domain=go Code=1 "failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees" UserInfo={NSLocalizedDescription=failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees}, Error Domain=go Code=1 "failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees" UserInfo={NSLocalizedDescription=failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees}, null)
2023-08-14 20:28:40.648 [ERR] BIND: Error in calling method 'addInvoice' with arguments: {argument: [10, 6, 10, 0, 16, 192, 132, 61, 18, 167, 1, 10, 11, 108, 115, 112, 100, 45, 115, 101, 99, 114, 101, 116, 18, 5, 66, 114, 101, 101, 122, 34, 66, 48, 51, 99, 98, 101, 97, 48, 101, 52, 56, 55, 55, 98, 97, 48, 98, 102, 48, 53, 54, 56, 97, 102, 97, 49, 97, 53, 56, 98, 55, 55, 55, 101, 50, 54, 101, 55, 97, 48, 100, 99, 48, 48, 52, 51, 57, 50, 97, 55, 49, 102, 57, 98, 52, 54, 98, 99, 57, 99, 48, 48, 100, 100, 54, 54, 100, 42, 18, 49, 57, 50, 46, 49, 54, 56, 46, 54, 56, 46, 54, 48, 58, 57, 55, 51, 54, 64, 232, 7, 73, 141, 237, 181, 160, 247, 198, 176, 62, 80, 144, 1, 88, 216, 4, 96, 40, 106, 33, 2, 86, 29, 238, 199, 110, 109, 160, 85, 229, 210, 159, 116, 114, 155, 216, 103, 40, 248, 34, 78, 126, 10, 179, 97, 141, 118, 28, 145, 126, 250, 183, 31, 120, 128, 137, 122, 26, 0]}.
2023-08-14 20:28:40.649 [ERR] BIND: Error in calling method 'addInvoice' with error: PlatformException(Method Error, Error Domain=go Code=1 "failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees" UserInfo={NSLocalizedDescription=failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees}, Error Domain=go Code=1 "failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees" UserInfo={NSLocalizedDescription=failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees}, null).
2023-08-14 20:28:40.652 [INF] BIND: Error Domain=go Code=1 "failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees" UserInfo={NSLocalizedDescription=failed to register payment with LSP RegisterPayment() error: rpc error: code = Unknown desc = checkPayment(1000000000, 1000000000) error: not enough fees}
#0      BreezBridge._invokeMethodWhenReady.<anonymous closure>.<anonymous closure> (package:breez/services/breezlib/breez_bridge.dart:946:11)
#1      _rootRunUnary (dart:async/zone.dart:1406:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#3      _FutureListener.handleError (dart:async/future_impl.dart:165:22)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#6      Future._completeError (dart:async/future_impl.dart:575:5)
#7      _rootRunUnary (dart:async/zone.dart:1406:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>

2023-08-14 20:28:41.109 [INF] BIND: LSP - has selected lsp ensuring reconnect
2023-08-14 20:28:41.109 [INF] BIND: before invoking method immediate getAccountInfo
getAccountInfo
2023-08-14 20:28:41.110 [INF] BIND: startCompleted completed: before invoking method immediate getAccountInfo
2023-08-14 20:28:41.110 [INF] BIND: LSP - already contains lsp peer, no need for reconnect

```

**Comment by kingonly** [comment]
As mentioned in the previous issue, we're not providing developer support for Breez mobile.
