### ISSUE TITLE
Breez app died (frozen blue screen)

### ISSUE THREAD

**Issue by MarnixCroes** [breez/breezmobile#1232]
Couldn't do anything anymore, had to restart Breez

### How To Reproduce?

1. Receive some corn via BTC address
2. Wait a while
3. After a while, at homescreen at the rop right a spinner appears (same icon as when syncing)
4. click on it
5. see `Breez is transferring funds` dialog
6. wait a bit
7. See ERROR
8. cannot do anything anymore, see screenshots

### Screenshots

![image](https://github.com/breez/breezmobile/assets/93143998/7d98de13-5188-4079-b168-50222120841f)

![image](https://github.com/breez/breezmobile/assets/93143998/0985bc68-77f2-4be4-a888-333addd614d5)

### Logs

I checked for the specific time, but logs are missing

### What type of machine are you observing the error on?

Pixel mobile

### Operating System

graphene OS

### Breez Version

latest,
1695315644

**Comment by JssDWt** [comment]
Can confirm this happened to me too.
I think this is the relevant stacktrace for me.

```
2023-10-13 10:14:17.791 [INF] BIND: Bad state: No element
#0      ListMixin.lastWhere (dart:collection/list.dart:180)
#1      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4994)
#2      _TransferFundsInProgressDialogState._pop (package:breez/routes/transfer_funds_in_progress_dialog.dart:50)
#3      _TransferFundsInProgressDialogState.initState.<anonymous closure> (package:breez/routes/transfer_funds_in_progress_dialog.dart:38)
#4      _rootRunUnary (dart:async/zone.dart:1406)
#5      _CustomZone.runUnary (dart:async/zone.dart:1307)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#9      _MultiStreamController.addSync (dart:async/stream_impl.dart:1044)
#10     _MultiControllerSink.add (package:rxdart/src/utils/forwarding_stream.dart:130)
#11     _StartWithStreamSink.onData (package:rxdart/src/transformers/start_with.dart:12)
#12     _rootRunUnary (dart:async/zone.dart:1406)
#13     _CustomZone.runUnary (dart:async/zone.dart:1307)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#16     _DelayedData.perform (dart:async/stream_impl.dart:515)
#17     _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#18     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#19     _rootRun (dart:async/zone.dart:1390)
#20     _CustomZone.run (dart:async/zone.dart:1300)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1208)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248)
#23     _rootRun (dart:async/zone.dart:1398)
#24     _CustomZone.run (dart:async/zone.dart:1300)
#25     _CustomZone.runGuarded (dart:async/zone.dart:1208)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

```
