### ISSUE TITLE
freeze when unsupported language is selected

### ISSUE THREAD

**Issue by ubbabeck** [breez/breezmobile#1243]
### General Description

If user has locale eg. Nynorsk 

### How To Reproduce?

1. Change to norsk nynorsk or another unsupported flutter language  on your iOS device
2. Open breezmobile
3. Go to security and backup --> app freezes 

### Logs

```
2023-10-27 11:13:44.623 [INF] BIND: Invalid argument(s): Invalid locale "nn_NO"
#0      _throwLocaleError (package:intl/src/intl_helpers.dart:204)
#1      verifiedLocale (package:intl/src/intl_helpers.dart:198)
#2      new DateFormat (package:intl/src/intl/date_format.dart:267)
#3      new DateFormat.yMd (package:intl/src/intl/date_format.dart:467)
#4      BreezDateUtils._yearMonthDayHourMinuteFormat (package:breez/utils/date.dart:12)
#5      BreezDateUtils.formatYearMonthDayHourMinute (package:breez/utils/date.dart)
#6      LastBackupText.build.<anonymous closure> (package:breez/routes/security_pin/security_and_backup/widgets/last_backup_text.dart:31)
#7      StreamBuilder.build (package:flutter/src/widgets/async.dart:444)
#8      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076)
#19     _rootRun (dart:async/zone.dart:1398)
#20     _CustomZone.run (dart:async/zone.dart:1300)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1208)
#22     _invoke (dart:ui/hooks.dart:147)
#23     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338)
#24     _drawFrame (dart:ui/hooks.dart:112)

```

### Operating System

iOS

### Breez Version

latest iOS

**Comment by ubbabeck** [comment]
Workaround --> use english or another langue as preferred langue.
