### ISSUE TITLE
Restore fails with DEBUG build

### ISSUE THREAD

**Issue by tlindi** [breez/breezmobile#871]
Tried to restore from Google Drive with Debug build. After selecting google account to restore from UI returns to start screen. 

Release Breez currently shows Offline - maybe related?

Debug log shows:

E/BREEZUI (11573): Error in method getDefaultOnChainFeeRate: API not ready
E/BREEZUI (11573): go.Universe$proxyerror: API not ready
E/BREEZUI (11573):      at bindings.Bindings.getDefaultOnChainFeeRate(Native Method)
E/BREEZUI (11573):      at java.lang.reflect.Method.invoke(Native Method)
E/BREEZUI (11573):      at com.breez.client.plugins.breez.breezlib.Breez$BreezTask.run(Breez.java:339)
E/BREEZUI (11573):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/BREEZUI (11573):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/BREEZUI (11573):      at java.lang.Thread.run(Thread.java:919)
I/flutter (11573): error invoking method immediate getDefaultOnChainFeeRate : PlatformException(API not ready, API not ready, Failed to invoke method getDefaultOnChainFeeRate, null)
I/flutter (11573): Error in calling method getDefaultOnChainFeeRate
I/GoLog   (11573): 2022-04-08 16:01:02.663 [ERR] BIND: error invoking method immediate getDefaultOnChainFeeRate : PlatformException(API not ready, API not ready, Failed to invoke method getDefaultOnChainFeeRate, null)
I/GoLog   (11573): 2022-04-08 16:01:02.664 [ERR] BIND: Error in calling method getDefaultOnChainFeeRate
I/GoLog   (11573): 2022-04-08 16:01:02.665 [INF] BIND: API not ready method: getDefaultOnChainFeeRate
I/GoLog   (11573): #0      BreezBridge._invokeMethodImmediate.<anonymous closure>.<anonymous closure> (package:breez/services/breezlib/breez_bridge.dart:791:11)
I/GoLog   (11573): #1      _rootRunUnary (dart:async/zone.dart:1434:47)
I/GoLog   (11573): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/GoLog   (11573): #3      _FutureListener.handleError (dart:async/future_impl.dart:177:22)
I/GoLog   (11573): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
I/GoLog   (11573): #5      Future._propagateToListeners (dart:async/future_impl.dart:799:13)
I/GoLog   (11573): #6      Future._completeError (dart:async/future_impl.dart:609:5)
I/GoLog   (11573): #7      _completeOnAsyncError (dart:async-patch/async_patch.dart:272:13)
I/GoLog   (11573): #8      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
I/GoLog   (11573): <asynchronous suspension>
I/GoLog   (11573):
I/BreezGAuthenticator(11573): Signed out
I/BreezGAuthenticator(11573): silentSignIn failed
I/BreezGAuthenticator(11573): silentSignIn continue to activity
I/BreezGAuthenticator(11573): Signing in using google activity
W/ActivityThread(11573): handleWindowVisibility: no activity for token android.os.BinderProxy@a9d6299
I/BreezGAuthenticator(11573): onActivityResult requestCode = 84 resultCode = 0 intent came back with result
D/Breez   (11573): App Resumed - OnPostResume called
I/BreezGAuthenticator(11573): Sign in Failed...
I/flutter (11573): App Resumed - flutter resume called, adding reconnect request
I/flutter (11573): Account is ready for payments
I/GoLog   (11573): 2022-04-08 16:01:12.777 [INF] BIND: App Resumed - flutter resume called, adding reconnect request
I/GoLog   (11573): 2022-04-08 16:01:12.777 [INF] BIND: Account is ready for payments

**Comment by tlindi** [comment]
Reply to self: learned about google APIs needed to setup GDrive connection.
